apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
